### ISSUE TITLE
Please give credit to fstab/cifs

### ISSUE THREAD

**Issue by onitake** [nelvadas/cifs-flexvolume-k8s#1]
It looks like your container uses the flexvolume script from: https://github.com/fstab/cifs

Wouldn't it be fair to mention this in the readme and give proper credit to the author?
I'm not affiliated with them, but I still think it would be nice to do so.

Aside from that, good work!

**Comment by nelvadas** [comment]
Hi @onitake , Sorry to forget liking fstab in the documnetation, Indeed you can see in dockerfile  we are not using a hardcopy of this file , we are relying on the original source file on github.
Doc updated.
Thanks
